local SCREEN_WIDTH, SCREEN_HEIGHT = gameplayVariables["screenSize"][1],gameplayVariables["screenSize"][2]

local CLOCK_IMG,CLOCK_DEFAULT_X,CLOCK_DEFAULT_Y,CLOCK_DIAMETER,CLOCK_COLOR,CLOCK_POST_GUI
local CLOCK_RADIUS,CLOCK_CENTER_X,CLOCK_CENTER_Y
local CLOCK_HOUR_IMG,CLOCK_HOUR_W,CLOCK_HOUR_H,CLOCK_HOUR_X,CLOCK_HOUR_Y,CLOCK_HOUR_ROT_POS_X,CLOCK_HOUR_ROT_POS_Y,CLOCK_HOUR_COLOR
local CLOCK_MINUTE_IMG,CLOCK_MINUTE_W,CLOCK_MINUTE_H,CLOCK_MINUTE_X,CLOCK_MINUTE_Y,CLOCK_MINUTE_ROT_POS_X,CLOCK_MINUTE_ROT_POS_Y,CLOCK_MINUTE_COLOR
local CLOCK_SECOND_IMG,CLOCK_SECOND_W,CLOCK_SECOND_H,CLOCK_SECOND_X,CLOCK_SECOND_Y,CLOCK_SECOND_ROT_POS_X,CLOCK_SECOND_ROT_POS_Y,CLOCK_SECOND_COLOR
local CLOCK_SETTING_FILE,CLOCK_SETTING_DEFAULT_TOGGLE

local CLOCK_X,CLOCK_Y = 0,0

	CLOCK0_IMG     = "images/clock_d.png"
	CLOCK_IMG       = "images/clock.png"
	CLOCK2_IMG       = "images/clock2.png"
CLOCK_SETTING_FILE           = "clock.xml"
CLOCK_SETTING_DEFAULT_TOGGLE = true

CLOCK_DEFAULT_X = SCREEN_WIDTH - SCREEN_WIDTH*0.2 + ( 70/1280 )  * SCREEN_WIDTH
CLOCK_DEFAULT_Y = ( 140/1024 ) * SCREEN_HEIGHT
function setSettings()
	CLOCK_DIAMETER  = SCREEN_HEIGHT * 0.13
	CLOCK1_COLOR     = tocolor(0,0,0, 255)
	CLOCK2_COLOR     = tocolor(255,255,255,255)
	CLOCK_POST_GUI  = false

	CLOCK_RADIUS   = CLOCK_DIAMETER / 2
	CLOCK_CENTER_X = CLOCK_X + CLOCK_RADIUS
	CLOCK_CENTER_Y = CLOCK_Y + CLOCK_RADIUS

	CLOCK_HOUR_IMG       = "images/whyzerbig.png"
	CLOCK_HOUR_W         = CLOCK_DIAMETER / 2.3 / 300 * 22
	CLOCK_HOUR_H         = CLOCK_DIAMETER / 2.3
	CLOCK_HOUR_X         = CLOCK_CENTER_X - CLOCK_HOUR_W / 2
	CLOCK_HOUR_Y         = CLOCK_Y + CLOCK_HOUR_H / 300 * 50 * 3
	CLOCK_HOUR_ROT_POS_X = 0
	CLOCK_HOUR_ROT_POS_Y = CLOCK_HOUR_H / 300 * 50
	CLOCK_HOUR_COLOR     = tocolor(255,255,255,255)

	CLOCK_MINUTE_IMG       = "images/whyzerbig.png"
	CLOCK_MINUTE_W         = CLOCK_DIAMETER / 2 / 300 * 22
	CLOCK_MINUTE_H         = CLOCK_DIAMETER / 2
	CLOCK_MINUTE_X         = CLOCK_CENTER_X
	CLOCK_MINUTE_Y         = CLOCK_Y + CLOCK_MINUTE_H / 300 * 50 * 2
	CLOCK_MINUTE_ROT_POS_X = 0
	CLOCK_MINUTE_ROT_POS_Y = CLOCK_MINUTE_H / 300 * 50
	CLOCK_MINUTE_COLOR     = tocolor(255,255,255,255)

	CLOCK_SECOND_IMG       = "images/whyzerseconds.png"
	CLOCK_SECOND_W         = CLOCK_DIAMETER / 1.7 / 280 * 13
	CLOCK_SECOND_H         = CLOCK_DIAMETER / 1.7
	CLOCK_SECOND_X         = CLOCK_CENTER_X - CLOCK_SECOND_W / 2
	CLOCK_SECOND_Y         = CLOCK_Y + CLOCK_SECOND_H / 280 * 40 * 1.5
	CLOCK_SECOND_ROT_POS_X = 0
	CLOCK_SECOND_ROT_POS_Y = CLOCK_SECOND_H / 280 * 40
	CLOCK_SECOND_COLOR     = tocolor(255,255,255,255)
end



local toggle = CLOCK_SETTING_DEFAULT_TOGGLE
local repos  = false

function handleClockStart()

	local xmlFile = xmlLoadFile(CLOCK_SETTING_FILE)
	if xmlFile then

		toggle  = xmlNodeGetAttribute(xmlFile,"enabled") ~= "false"
		CLOCK_X = tonumber(xmlNodeGetAttribute(xmlFile,"posX")) or CLOCK_DEFAULT_X
		CLOCK_Y = tonumber(xmlNodeGetAttribute(xmlFile,"posY")) or CLOCK_DEFAULT_Y
		

		xmlUnloadFile(xmlFile)
	else

		CLOCK_X = CLOCK_DEFAULT_X
		CLOCK_Y = CLOCK_DEFAULT_Y
		


	end
	

	setSettings()
	


end
addEventHandler("onClientResourceStart",getResourceRootElement(),handleClockStart)






function renderClock()
	local time = getRealTime()
	
	local hour   = time.hour % 12 
	local minute = time.minute
	local second = time.second
	
	minute = minute + second / 60 
	hour   = hour   + minute / 60 
	
	local hourRot   = 360 * ( hour   / 12 )
	local minuteRot = 360 * ( minute / 60 )
	local secondRot = 360 * ( second / 60 )
	dxDrawImage(CLOCK_X-27,CLOCK_Y-77,CLOCK_DIAMETER+55,CLOCK_DIAMETER+133,CLOCK0_IMG) 
	dxDrawImage(CLOCK_X,CLOCK_Y,CLOCK_DIAMETER,CLOCK_DIAMETER,CLOCK_IMG,0,0,0,CLOCK1_COLOR,CLOCK_POST_GUI)
	dxDrawImage(CLOCK_X,CLOCK_Y,CLOCK_DIAMETER,CLOCK_DIAMETER,CLOCK2_IMG,0,0,0,CLOCK2_COLOR,CLOCK_POST_GUI)
	
	dxDrawImage(CLOCK_HOUR_X,CLOCK_HOUR_Y,CLOCK_HOUR_W,CLOCK_HOUR_H,CLOCK_HOUR_IMG,hourRot,CLOCK_HOUR_ROT_POS_X,CLOCK_HOUR_ROT_POS_Y,CLOCK_HOUR_COLOR,CLOCK_POST_GUI)
	
	dxDrawImage(CLOCK_MINUTE_X,CLOCK_MINUTE_Y,CLOCK_MINUTE_W,CLOCK_MINUTE_H,CLOCK_MINUTE_IMG,minuteRot,CLOCK_MINUTE_ROT_POS_X,CLOCK_MINUTE_ROT_POS_Y,CLOCK_MINUTE_COLOR,CLOCK_POST_GUI)
	
	dxDrawImage(CLOCK_SECOND_X,CLOCK_SECOND_Y,CLOCK_SECOND_W,CLOCK_SECOND_H,CLOCK_SECOND_IMG,secondRot,CLOCK_SECOND_ROT_POS_X,CLOCK_SECOND_ROT_POS_Y,CLOCK_SECOND_COLOR,CLOCK_POST_GUI)
end
